### ISSUE TITLE
Implement leaderboard model/entity and functions

### ISSUE THREAD

**Issue by coxmars** [ByteBuildersLabs/ByteBeastsBackend#28]
Implement a leaderboard model that tracks and ranks players based on their achievements, battle wins, and other key performance metrics. 

- You can use this PR as reference https://github.com/ByteBuildersLabs/ByteBeastsBackend/pull/39 consider that here we are using static elements, but use this library https://github.com/keep-starknet-strange/alexandria to do it dinamically and be sure it is working.
- Please create a new PR, include the model/entity and the functions needed for this flow like get rank player by id, a list of 10 top players etc etc you can consider the implementation of the last PR as examples and you can add more if you think is useful.
- Follow the Contributions Guidelines and PR guidelines/example etc.
- If you need help just ask me here in a comment or ping me in Telegram in the group channel for external contributors.

Thanks for your time, please send a comment with your approach/solution, be creative and use a technical explanation and avoid ChatGPT or AI comments.

**Comment by stevencartavia** [comment]
hello, I would love to work on this! 

I've worked on gaming, I have contributions in Cairo.

**Comment by MrRoudyk** [comment]
May I pick this up?

**Comment by Abeeujah** [comment]
Hello, I'm a Developer proficient in Cairo, I've gone through the draft PR and the Alexandria package, I'm also in the telegram and would ping you anytime I encounter anything that's unclear; Can I work on this issue?

**Comment by mimisavage** [comment]
Can I tackle this one?

**Comment by Supa-mega** [comment]
May I handle this issue?

**Comment by danielcdz** [comment]
@beeguy74 all yours, send a PR as soon as you can 👍
