### ISSUE TITLE
Add to the README a section of requirements or dependencies to run the project

### ISSUE THREAD

**Issue by danielcdz** [ByteBuildersLabs/ByteBeastsBackend#48]
## Summary
- Transcript this [guide](https://book.dojoengine.org/getting-started) of the official Dojo Engine Book about the prerequisites to run a Dojo project into our README.

**Comment by diegoTech14** [comment]
Hey @danielcdz, I'm a software engineer from Costa Rica, I would love to help with this issue. Can I work on it?

**Comment by danielcdz** [comment]
@diegoTech14 go for it!

**Comment by diegoTech14** [comment]
Thank you sir! I will start ASAP
