### ISSUE TITLE
Enhance Documentation in the Project

### ISSUE THREAD

**Issue by danielcdz** [ByteBuildersLabs/ByteBeastsBackend#76]
## 📖 Description
- We want to improve the documentation organization in the project, and for this, we need the following:
  - Create a new `docs` directory
  - Inside the new dir create a `contribution` directory 
  - Place the Contribution guidelines inside of it
- Another improvement we want is to create a template for the issues we will make in the future, this can be done by adding a template.md inside the .github directory, follow the pull request MD file as an example
   - Inside the .github, create a new directory called `templates` and place both the pull request and the new issue templates in it. 
   - Use the descriptions from the ODHack9 issues in this repository as references to create the template. Feel free to add any additional points you think would be helpful!

## 📦 Deliverable
- `docs` directory created
- Contribution guidelines moved to the correct place
- Issue template created
- Both templates moved to the correct place 

## ⚠️ Notes
- This issue is specifically for newcomers, those just starting out with OnlyDust and open-source contributions. If you're an experienced developer, please leave this issue to someone who is new. There are other issues better suited for seasoned developers and OSS contributors!

**Comment by akintewe** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I'm thrilled about the chance to contribute to ODHack9 for the first time as a computer science graduate with C# skills and increasing Cairo knowledge. Even though I'm new to contributing to open-source projects, I've learned the value of well-organized project structures and good documentation from my academic experience.

### How I plan on tackling this issue
I would begin by comprehending the present project structure and closely examining the pull request template as a guide. The first thing I would do is create the new 'docs' directory and arrange the contribution rules, making sure everything is clearly organized and simple to use. In order to develop a thorough template that enables future contributors to include all required information, I would examine the trends in previous ODHack9 issues.
I can't wait to learn more and help make this project more approachable for novices like me. I think this is the ideal chance for me to start my open-source career and contribute significantly to the project's structure.
:)

**Comment by derianrddev** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
Hello, I'm Derian, a software engineer focused on full-stack web development, and I'm currently part of Dojo Coding. I would like to work on this issue and gain more experience. It would be an honor if this were my first issue on OnlyDust. I would really appreciate the opportunity to contribute and be part of this project!

### How I plan on tackling this issue
I will study the codebase to understand the current structure and functionality.
I will carefully read the issue description to understand the problem that needs to be solved.
I will leverage all the resources provided in the issue to get a better grasp of the task.
If I have any doubts, I will ask questions as soon as possible in the Telegram group.
I will open a PR and wait for your feedback.
I will make the necessary changes based on the PR review.

**Comment by sanieni6** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
hi there, I am Luis a front-end developer with 2 years of experience, I will be glad to contribute to this project my man.

### How I plan on tackling this issue
I think this issue can be easily approached this way:
1. Create the new docs/dir/ direrectory
2. Drop the CONTRIBUTION.md guilines there
3. Add a template.md inside the .GitHub/templates beside the PULL_REQUEST_TEMPLATE.md


This is my first approach after make a quick check of your code, however it can be more changes related 
this issue. Let's rock!!

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
ello @ i'm a frontend developer and an experienced technical writer i would love to work on this issue 
Pleasee kindly assign :)

**Comment by petersdt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
am a  junior developer beginning a path in frontend development and technical writing. Kindly assign me this issue to help boast and improve my contribution portfolio to open source contribution

### How I plan on tackling this issue
Step 1: Create a new docs directory
I'll navigate to the root of my repository on GitHub and click on "Add file" > "Create new file." I'll name the file "docs" (without extension).

Step 2: Move the Contribution guidelines
Next, I'll create a new file named "docs/contribution.md." Then, I'll copy the existing Contribution guidelines into this file.

Step 3: Create an issue template
Now, I'll create a new file named ".github/templates/pull_request.md." I'll copy the content of the existing pull request template into this file.

Step 4: Add a new issue template
Finally, I'll create a new file named ".github/templates/issue_template.md." I'll copy the content of the existing issue template into this file.

creating a PR in less that 72hrs

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
i have experience in game dev as well as blockchain previously as personal projects and OS, so hoping to make use of them here and mark my first odhack contribution

### How I plan on tackling this issue
let me put my skills to test

**Comment by pheobeayo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
I am a Web3 front-end developer skilled in technical documentation and software development. I greatly understand technologies like JavaScript, Typescript, Cairo, Rust and Solidity. I have contributed successfully to open-source projects like Stark Quest and Speedrun scaffold-stark.

### How I plan on tackling this issue
My Approach includes Pull Request (PR) includes:
- Reviewing of existing Documentation:
By thoroughly reading the current documentation, including README files, code comments, and any other relevant documentation provided in the repository.
Identify areas that are unclear, outdated, or missing crucial information that would benefit users and developers.
-Create the template and contribution directory as instructed.
- Note changes and define all code snippets and technical terms simply.
- Create a Pull Request (PR).
- Request for a Review.
- Make changes based on the Review of the PR.

**Comment by BrunoAmbricca** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
Hey guys, Bruno here from the dojo coding community. I´ve been working for the past 4 years with c# and in big companies like the one Im right one (Mercado Libre) so I have encountered a lot of documentation.

### How I plan on tackling this issue
I would follow your guidelines on how to create the docs and document all the cases

**Comment by josephpdf** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
Hi!, my name is Joseph Poveda.
I am a student of the Systems Programming degree, I am a recent member of the Dojo Coding community, where I am getting started in the world of Web3.
I have basic knowledge of different programming languages ​​and thanks to this I hope to be able to resolve the issue.

### How I plan on tackling this issue
To address this issue, I would start by creating the requested new directory structure, specifically the "docs" directory and within it, a "contribution" subdirectory to host the contribution guidelines. Then I would review the current guidelines file and move it to the new location. For templates, I would create the ".github/templates" directory and place the files for pull requests and issues there, following the example provided in the ODHack9 platform. I would adapt the issue descriptions based on the repository requirements and add additional points that you consider useful.

**Comment by YarexEspinoza17** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bytebeasts).

### My background and how it can be leveraged
Hi 

I'm a software engineer from Costa Rica and a member of Dojo Coding, I'm new to the community. I've worked with technologies like JavaScript, Node.js, PhP, Java, C#, Typescript. I'd love to have the opportunity to help with this problem and contribute to your project.



### How I plan on tackling this issue
For this issue I will:

1.Create directories:

Create the docs/ directory.
Inside docs/, create the contribution/ directory.
Move the contribution guidelines to the docs/contribution/ directory.

2.GitHub templates:

Create the .github/templates/ directory.
Add the template.md file inside .github/templates/ for the issue template, using the ODHack9 issue descriptions as a reference.
Move the existing pull request template to the .github/templates/ directory.

3.Deliverables:

A docs/ directory containing the contribution guidelines.
A .github/templates/ directory containing both the issue and pull request templates.

Looking forward to your feedback!

Best regards,

Yarex Espinoza Naranjo.

**Comment by aniruddhaaps** [comment]
I'm a cairo dev. A new-comer here, willing and ready to contribute to solve the issue.

**Comment by sandragcarrillo** [comment]
Would love to contribute on this issue

I have been doing an internship at Nethermind and been helping with some documentation as I'm learning Cairo at the same time. this would be a great project to keep contributing to open source projects

**Comment by GideonBature** [comment]
Hi, I'm Gideon Bature, a Software Engineer and quite new on OnlyDust I'll be working on issue #76.

I estimate this will take 5 days to complete.

This is how I would tackle this issue:

I will use the descriptions from the ODHack9 issues in this repository as references to create the template.

I will improve the documentation organization in the project, by doing the following:

1. Create a new docs directory
2. Inside the new directory create a contribution directory
3. Place the Contribution guidelines inside of it
4. Add a template.md inside the .github directory, by following the pull request MD file as an example
5. Inside the .github, I am going to create a new directory called templates and place both the pull request and the new issue templates in it.

**Comment by Jemiiah** [comment]
Can I work on this issue have great experience on documentation issue with an ETA : 24 hours max

**Comment by rogeralbp** [comment]
I have experience with markdowns , the use of the differents components to make the documentation clearer as possible for the contributors, I would love the help the team with this
